CREATE DATABASE cars;
-- GRANT ALL PRIVILEGES ON DATABASE cars TO program;

CREATE DATABASE rentals;
-- GRANT ALL PRIVILEGES ON DATABASE rentals TO program;

CREATE DATABASE payment;
-- GRANT ALL PRIVILEGES ON DATABASE payments TO program;