name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.6.3
      - name: cars build
        run: mvn -f cars/pom.xml --batch-mode --update-snapshots clean install -DskipTests
      - name: payment build
        run: mvn -f payment/pom.xml --batch-mode --update-snapshots clean install -DskipTests
      - name: rental build
        run: mvn -f rental/pom.xml --batch-mode --update-snapshots clean install -DskipTests
      - name: service-registry build
        run: mvn -f service-registry/pom.xml --batch-mode --update-snapshots clean install -DskipTests
      - name: gateway build
        run: mvn -f gateway/pom.xml --batch-mode --update-snapshots clean install -DskipTests

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: lab_data/variants/v3/postman/collection.json
          environment: lab_data/variants/v3/postman/environment.json
          delayRequest: 150
          reporters: '[ "cli" ]'

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: 'library/postgres:13,gateway,rental,payment,cars,service-registry'
          tail: '100'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 2
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v